services:
  api:
    build: .
    container_name: artifact_api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@mongodb:${DATABASE_PORT}/${DATABASE_NAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  mongodb:
    image: mongo:4.4
    container_name: artifact_mongo
    restart: always
    ports:
      - "${DATABASE_PORT}:27017"
    volumes:
      - artifact_mongo_data:/data/db

volumes:
  artifact_mongo_data:
