services:
  metadata-store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata-store
    ports:
      - "8081:8080"
    environment:
      - JENA_TDB2_LOCATION=${JENA_TDB2_LOCATION}
      - METADATA_STORE_BASE_URI=${METADATA_STORE_BASE_URI}
    volumes:
      - metadata-store-data:/app/data
    restart: unless-stopped

volumes:
  metadata-store-data:
    name: metadata-store-data